name: py310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - basicsr==1.4.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grpcio==1.75.1
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.0
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lpips==0.1.4
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mmcv-full==1.5.0
      - modelscope==1.31.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numpy==1.26.0
      - nvidia-ml-py==13.580.82
      - nvitop==1.5.3
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.0
      - protobuf==6.32.1
      - psutil==7.1.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - six==1.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - thop==0.1.1-2209072238
      - tifffile==2025.5.10
      - timm==1.0.21
      - tomli==2.3.0
      - torch==1.11.0+cu113
      - torchstat==0.0.7
      - torchvision==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - warmup-scheduler==0.3
      - werkzeug==3.1.3
      - yapf==0.43.0
prefix: /root/miniconda3/envs/py310
